name: Terraform Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env: 
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=Azure init

      - name: Terraform Validate
        run: terraform -chdir=Azure validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' 
        run: terraform -chdir=Azure plan -out=tfplan 

      - name: Upload Plan
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.sha }}
          path: Azure/tfplan

      - name: Download Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/download-artifact@v4
        with:
          name: plan-${{ github.sha }} 
          path: Azure/

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=Azure apply -auto-approve Azure/tfplan
