name: Terraform Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Passa o ID da Assinatura
        run: terraform -chdir=Azure init

      - name: Terraform Validate
        run: terraform -chdir=Azure validate

      - name: Terraform Plan
        run: terraform -chdir=Azure plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Azure/tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=Azure apply -auto-approve tfplan

      - name: Defender for Cloud Assessments
        run: |
          az security assessment list --query "[].{Name:name, Status:status.code}" -o table
